FROM node:15.5.1 AS builder
COPY ./web /app
RUN cd /app && yarn install && npm run build

FROM nginx:1.19.6-alpine

RUN echo $' server {\n\
    listen       30294;\n\
    server_name  localhost;\n\
\n\
    location / {\n\
        root   /usr/share/nginx/html;\n\
        index  index.html index.htm;\n\
        try_files $uri $uri/ =404;\n\
    }\n\
}' > /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 30294