FROM ruby:3.0-alpine AS builder

RUN apk add --update build-base

WORKDIR /app

ADD ./api /app
ADD ./parser /parser
RUN gem install bundler:2.2.4
RUN bundle config set --local deployment 'true'
RUN bundle install

RUN echo "/3d6+4" > /app/CHECKS

FROM ruby:3.0-alpine
WORKDIR /app
COPY --from=builder /app /app
COPY --from=builder /parser /parser
RUN bundle config --local path vendor/bundle

CMD ["bundle", "exec", "rackup", "-o", "0.0.0.0", "-p", "5000"]

