# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

group :development do
  gem 'rubocop', require: false
  gem 'pry'
  gem 'solargraph'
end

group :test do
  gem 'rspec', '~> 3.10'
  gem 'simplecov', require: false
end
