# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "r3d6-parser", path: "../parser"

gem "sinatra", "~> 2.1"

gem "puma", "~> 5.1"
