# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "r3d6-parser", path: "../parser"

gem "puma", "~> 5.1"

gem "roda", "~> 3.41"
